manifest:
  self:
    path: application
  remotes:
    - name: nrf
      url-base: https://github.com/nrfconnect
    - name: you
      url-base: https://github.com/CuSither

  projects:
    - name: sdk-nrf
      remote: nrf
      path: nrf
      revision: v3.0.2
      import:
        path-prefix: external
      clone-depth: 1
    - name: zephyr
      remote: you
      repo-path: sdk-zephyr-ono
      revision: fix/spi-rtio-trans-op
      import:
        path-prefix: external
